apiVersion: batch/v1
kind: Job
metadata:
  name: job-type-parallelism-busybox
spec:
  parallelism: 3
  template:
    metadata:
      name: busybox
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["echo", "hello"]
      restartPolicy: Never