apiVersion: batch/v1
kind: Job
metadata:
  name: test-job-active-deadline-seconds
spec:
  activeDeadlineSeconds: 20
  template:
    metadata:
      name: busybox
    spec:
      restartPolicy: Never
      containers:
      - name: busybox
        image: busybox
        command: ["echo","hello"]