apiVersion: v1
kind: Service
metadata:
  name: test-clusterip-nginx
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - name: tcp-80
      port: 8080
      protocol: TCP
      targetPort: 80
    - name: udp-80
      port: 8080
      protocol: UDP
      targetPort: 80
