apiVersion: v1
kind: Service
metadata:
  name: test-clusterip-externalip-invalid
spec:
  type: ClusterIP
  externalIPs:
   - 10.9.8.7
  selector:
    app: nginx
  ports:
    - port: 8080
      targetPort: 80