apiVersion: v1
kind: Service
metadata:
  name: test-loadbalancer-nginx-udp
spec:
  type: LoadBalancer
  loadBalancerIP: ${FIP}
  selector:
    app: nginx
  ports:
    - name: udp-80
      port: 8080
      protocol: UDP
      targetPort: 80
    - name: udp-443
      port: 6443
      protocol: UDP
      targetPort: 443
