apiVersion: v1
kind: Service
metadata:
  name: test-loadbalancer-nginx-used
spec:
  type: LoadBalancer
  loadBalancerIP: ${FIP}
  selector:
    app: nginx
  ports:
    - name: tcp-80
      port: 8080
      protocol: TCP
      targetPort: 80
    - name: tcp-443
      port: 6443
      protocol: TCP
      targetPort: 443
