apiVersion: v1
kind: Service
metadata:
  name: test-loadbalancer-mysql
spec:
  type: LoadBalancer
  loadBalancerIP: ${FIP}
  selector:
    app: mysql
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
