apiVersion: v1
kind: Pod
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  containers:
  - name: wordpress
    image: wordpress:4.8-apache
    env:
    - name: WORDPRESS_DB_HOST
      value: mysql
    - name: WORDPRESS_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-password
          key: password
    ports:
    - containerPort: 80
      name: wordpress
    resources:
      limits:
        memory: 1000Mi
      requests:
        memory: 1000Mi

