apiVersion: v1
kind: Pod
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  containers:
  - name: wordpress
    image: wordpress:4.9.5-apache
    env:
    - name: WORDPRESS_DB_HOST
      value: mysql
    - name: WORDPRESS_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-password
          key: password
    ports:
    - containerPort: 80
      name: wordpress
    volumeMounts:
      - name: wp-data
        mountPath: /var/www/html
# leave it default
#    resources:
#      limits:
#        memory: 1000Mi
#      requests:
#        memory: 1000Mi
#

  volumes:
    - name: wp-data
      flexVolume:
        options:
          # volumes from `pi get volumes`
          volumeID: wp-data
