apiVersion: v1
kind: Pod
metadata:
  name: test-alpine-quay-private-image-without-secret
spec:
  containers:
  - name: private-reg-container
    image: quay.io/xjimmyshcn/busybox
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
