apiVersion: v1
kind: Pod
metadata:
  name: test-alpine-gcr-invalid-image
spec:
  containers:
  - name: alpine
    image: gcr.io/google-containers/alpine-with-bash
    command: ["echo", "hello"]
  restartPolicy: Never