apiVersion: v1
kind: Pod
metadata:
  name: test-runonce
  labels:
    app: test
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["echo","hello",";","sleep","10"]
  restartPolicy: Never
