# pi create secret docker-registry regcred-dockerhub-invalid --docker-username=xjimmyshcn --docker-password='xxxxxxxxxxxx' --docker-email=xjimmyshcn@gmail.com
apiVersion: v1
kind: Pod
metadata:
  name: test-alpine-dockerhub-private-image-with-invalid-secret
spec:
  containers:
  - name: private-reg-container
    image: xjimmyshcn/alpine:46
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
  imagePullSecrets:
  - name: regcred-dockerhub-invalid