apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-volume
  labels:
    app: nginx
    role: web
spec:
  containers:
  - name: nginx
    image: oveits/docker-nginx-busybox
    volumeMounts:
      - name: persistent-storage
        mountPath: /data
  volumes:
    - name: persistent-storage
      flexVolume:
        options:
          volumeID: nginx-data
