apiVersion: v1
kind: Pod
metadata:
  name: test-busybox-ecr-private-image-with-secret
spec:
  containers:
  - name: private-reg-container
    image: 450256631915.dkr.ecr.ap-southeast-1.amazonaws.com/busybox:latest
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
