# pi create secret docker-registry regcred-quay --docker-username=xjimmyshcn --docker-password='xxxxxxxxxxxx' --docker-server=quay.io --docker-email=none
apiVersion: v1
kind: Pod
metadata:
  name: test-alpine-quay-private-image-with-secret
spec:
  containers:
  - name: private-reg-container
    image: quay.io/xjimmyshcn/busybox
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
  imagePullSecrets:
  - name: regcred-quay