# pi create secret docker-registry regcred-gitlab --docker-username=xjimmy --docker-password='xxxxxxxxxxxx' --docker-email=xjimmyshcn@gmail.com --docker-server=registry.gitlab.com
apiVersion: v1
kind: Pod
metadata:
  name: test-alpine-gitlab-private-image-with-secret
spec:
  containers:
  - name: private-reg-container
    image: registry.gitlab.com/xjimmy/busybox:latest
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
  imagePullSecrets:
  - name: regcred-gitlab
