apiVersion: v1
kind: Pod
metadata:
  name: test-alpine-dockerhub-private-image-with-not-exist-secret
spec:
  containers:
  - name: private-reg-container
    image: xjimmyshcn/alpine:46
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
  imagePullSecrets:
  - name: regcred-not-exist