apiVersion: v1
kind: Pod
metadata:
  name: test-volume-gitrepo
  labels:
    name: test
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /mypath
      name: git-volume
  volumes:
  - name: git-volume
    gitRepo:
      repository: "https://github.com/hyperhq/pi.git"
      revision: "2555b80628a1f3fc241798bb3f69e8f76ade4360"
